#!/bin/bash
#        Author: Zach.Wang
#        Create: 2018-08-28 10:40:37
# how to
# cat safety-rm >> /etc/bashrc && source /etc/bashrc
# cron.monthly: cleartrash && mkdir -pv `date +"%Y-%m"`
trash_path=’/data/.trash’
NOW=`date +"%Y-%m"`
CUR_TRASH=$trash_path/$NOW

if [ ! -d $trash_path ]; then
mkdir -p $trash_path
fi

alias rm=trash
alias rl=’ls $trash_path’
alias unrm=restorefile

function RmHistory()
{
  if [[ $1 -eq killed ]];then
    echo "`date +'%Y-%m-%d-%H:%M'`" "`pwd`" "==> x" >> $trash_path/TrashFile-`date +%Y`.log
  fi
  if [[ $1 -eq recover ]];then
    echo "`date +'%Y-%m-%d-%H:%M'`" "`pwd`" "==> recover" >> $trash_path/TrashFile-`date +%Y`.log
  fi
}

function restorefile()
{
  mv -i $CUR_TRASH/$@ ./
  RmHistory recover
}

function trash()
{
  mv $@ $CUR_TRASH/
  RmHistory killed
}

function cleartrash()
{
read -p “Do you want to empty the trash?[y/n]” confirm
[ $confirm == ‘y’ ] || [ $confirm == ‘Y’ ] ls -ih > $trash_path/$NOW.log && /bin/rm -rf ~$CUR_TRASH/*
}