route:
  # The labels by which incoming alerts are grouped together. For example,
  # multiple alerts coming in for cluster=A and alertname=LatencyHigh would
  # be batched into a single group.
  group_by: ['alertname']

  # When a new group of alerts is created by an incoming alert, wait at
  # least 'group_wait' to send the initial notification.
  # This way ensures that you get multiple alerts for the same group that start
  # firing shortly after another are batched together on the first 
  # notification.
  group_wait: 5s

  # When the first notification was sent, wait 'group_interval' to send a batch
  # of new alerts that started firing for that group.
  group_interval: 1m

  # If an alert has successfully been sent, wait 'repeat_interval' to
  # resend them.
  repeat_interval: 3h 

  # A default receiver
  receiver: zach
  match_re:
    service: mysql|oracle
  smtp_from: pop.qq.com

templates: 
 - 'templates/*.tmpl'

receivers:
- name: 'zach'
  webhook_configs:
  - url: http://192.168.0.53:8080
  email_configs:
  - to: 'wzq1397@live.cn'
  html: '{{ template "email.ZACH.html" . }}'
  headers: { Subject: "[WARN] 报警邮件" }