global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  external_labels:
    monitor: 'codelab-monitor'

  rule_files:
    - rules/zach.rules
    - rules/zach2.rules
    
  evaluation_interval: 30s
  
scrape_configs:    
  - job_name: 'node-exporter'
    static_configs:
  - targets: ['172.30.100.10:9100']
    labels:
      hostname: 'web1'
  - targets: ['172.30.100.11:9100']
    hostname: 'web2'
  - targets: ['172.30.100.12:9100']
    hostname: 'web3'
